name: Deploy to Server

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 检查文件结构
      - name: List files
        run: |
          pwd
          ls -la
          ls -la nginx/
          echo "Checking backend files:"
          ls -la server.js || echo "server.js not found"
          ls -la init.sql || echo "init.sql not found"
          ls -la package.json || echo "package.json not found"
          ls -la config/database.js || echo "database.js not found"

      # 部署 Nginx 配置
      - name: Deploy Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./nginx/claw.ink.conf"
          target: "/www/server/panel/vhost/nginx"
          strip_components: 1

      # 部署静态文件到网站目录
      - name: Deploy static files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: |
            public/
          target: "/www/wwwroot/claw.ink"
          strip_components: 1
          overwrite: true
          exclude: |
            public/README.md
            public/.git*
            public/*.log

      # 部署后端文件
      - name: Deploy backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "."
          target: "/opt/clawcloud"
          strip_components: 0
          overwrite: true
          exclude: |
            .git*
            node_modules
            public
            nginx

      # 重启服务
      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # 检查目录和文件
            echo "Checking directories and files..."
            ls -la /www/wwwroot/claw.ink
            ls -la /opt/clawcloud
            
            # 检查 Node.js 版本和环境
            echo "Checking Node.js environment..."
            node -v
            npm -v
            
            # 重启后端服务
            cd /opt/clawcloud
            mkdir -p config logs data
            touch logs/error.log
            
            # 设置数据库目录
            export SQLITE_DB_PATH="/opt/clawcloud/data/database.sqlite"
            
            # 初始化数据库
            if [ ! -f "$SQLITE_DB_PATH" ]; then
                sqlite3 "$SQLITE_DB_PATH" < init.sql
            fi
            
            # 确保网站日志目录存在
            sudo mkdir -p /www/wwwlogs
            sudo chown -R $USER:$USER /www/wwwlogs
            
            # 安装编译工具
            sudo apt-get update
            sudo apt-get install -y python3 make gcc g++ build-essential
            
            # 清理并重新安装依赖
            rm -rf node_modules
            rm -rf package-lock.json
            npm install
            
            # 重新编译 SQLite3
            npm rebuild better-sqlite3
            
            # 启动服务并检查状态
            echo "Starting backend service..."
            pm2 delete clawcloud || true
            pm2 start server.js --name clawcloud
            pm2 save
            
            # 等待服务启动
            sleep 5
            
            # 检查服务状态
            echo "Checking service status..."
            pm2 list
            pm2 logs clawcloud --lines 20
            
            # 检查端口占用
            echo "Checking port status..."
            netstat -tulpn | grep LISTEN
            
            # 检查 Nginx 配置和状态
            echo "Checking Nginx status..."
            sudo systemctl is-active nginx || sudo systemctl start nginx
            nginx -t && nginx -s reload
            systemctl status nginx
            
            # 测试 API 连接
            echo "Testing API connection..."
            curl -I http://localhost:3000/api/categories || echo "API not responding"
            
            # 检查错误日志
            echo "Checking error logs..."
            tail -n 50 /opt/clawcloud/logs/error.log || echo "No error log found"
            tail -n 50 /www/wwwlogs/claw.ink.error.log || echo "No Nginx error log found"
