name: Deploy to Server

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 检查文件结构
      - name: List files
        run: |
          pwd
          ls -la
          ls -la nginx/

      # 部署 Nginx 配置
      - name: Deploy Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./nginx/claw.ink.conf"
          target: "/www/server/panel/vhost/nginx"
          strip_components: 1

      # 部署静态文件到网站目录
      - name: Deploy HTML files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/*.html"
          target: "/www/wwwroot/claw.ink"
          strip_components: 1
          overwrite: true

      - name: Deploy assets
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/assets"
          target: "/www/wwwroot/claw.ink"
          strip_components: 1
          overwrite: true

      - name: Deploy CSS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/css/font.css"
          target: "/www/wwwroot/claw.ink/css"
          strip_components: 2
          overwrite: true

      - name: Deploy JS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/js/common.js"
          target: "/www/wwwroot/claw.ink/js"
          strip_components: 2
          overwrite: true

      # 部署后端文件
      - name: Deploy backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: |
            server.js
            init.sql
            package.json
            .env
          target: "/opt/clawcloud"
          strip_components: 0

      # 重启服务
      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # 重启后端服务
            cd /opt/clawcloud
            npm install
            pm2 restart clawcloud || pm2 start server.js --name clawcloud
            
            # 测试并重载 Nginx 配置
            nginx -t && nginx -s reload
