name: Deploy to Server

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Public directory contents:"
          ls -la public/

      # 部署静态文件到网站目录
      - name: Deploy static files to website
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/**"  # 使用 glob 模式包含所有子目录和文件
          target: "/opt/1panel/apps/openresty/openresty/www/sites/claw.ink/index"
          strip_components: 1
          overwrite: true
          debug: true

      # 部署应用文件到应用目录
      - name: Deploy application files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: |
            config/
            server.js
            package.json
            package-lock.json
            .env
          target: "/opt/clawcloud"
          strip_components: 0

      # 设置 Node.js 并安装依赖
      - name: Setup Node.js and install dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt/clawcloud
            npm install
            pm2 restart clawcloud || pm2 start server.js --name clawcloud
