name: Deploy to Server

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Public directory contents:"
          ls -la public/

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Create necessary directories
        run: |
          mkdir -p data
          mkdir -p logs

      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: |
            public/
            config/
            server.js
            package.json
            package-lock.json
            .env
          target: "/opt/clawcloud"
          strip_components: 0

      - name: Execute remote commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt/clawcloud
            npm install
            pm2 restart clawcloud || pm2 start server.js --name clawcloud

      - name: Deploy static files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "public/"
          target: "/opt/1panel/apps/openresty/openresty/www/sites/claw.ink/index"
          strip_components: 1
          overwrite: true
          debug: true
