name: Deploy to Server

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # 检查文件结构
      - name: List files
        run: |
          pwd
          ls -la
          ls -la nginx/
          echo "Checking backend files:"
          ls -la server.js || echo "server.js not found"
          ls -la init.sql || echo "init.sql not found"
          ls -la package.json || echo "package.json not found"
          ls -la config/database.js || echo "database.js not found"

      # 部署 Nginx 配置
      - name: Deploy Nginx config
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "./nginx/claw.ink.conf"
          target: "/www/server/panel/vhost/nginx"
          strip_components: 1

      # 部署静态文件到网站目录
      - name: Deploy static files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: |
            public/*
          target: "/www/wwwroot/claw.ink"
          strip_components: 1
          overwrite: true
          exclude: |
            public/README.md
            public/.git*
            public/*.log

      # 部署后端文件
      - name: Deploy backend files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "."
          target: "/opt/clawcloud"
          strip_components: 0
          overwrite: true
          exclude: |
            .git*
            node_modules
            public
            nginx

      # 重启服务
      - name: Restart services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # 创建并设置日志目录
            sudo mkdir -p /www/wwwlogs
            sudo touch /www/wwwlogs/claw.ink.log /www/wwwlogs/claw.ink.error.log
            sudo chown -R www-data:www-data /www/wwwlogs
            sudo chmod 755 /www/wwwlogs
            sudo chmod 644 /www/wwwlogs/claw.ink.*
            
            # 设置网站目录权限
            sudo mkdir -p /www/wwwroot/claw.ink
            sudo chown -R www-data:www-data /www/wwwroot/claw.ink
            sudo chmod -R 755 /www/wwwroot/claw.ink
            
            # 检查网站文件
            echo "Checking website files:"
            ls -la /www/wwwroot/claw.ink/
            
            # 检查 Nginx 配置
            nginx -t
            
            # 重启 Nginx
            sudo systemctl restart nginx
            
            # 检查 Nginx 状态
            sudo systemctl status nginx
            
            # 测试网站访问
            curl -H "Host: claw.ink" http://localhost/
